Repository DO-SOPT-CDS-APP-2/CDS-APP-2-iOS, pull requests merged in 2023-12, with the labels that each got.

#69 [Network] #68 - HatCategory에서 HatDetail로 push, ImageURL 적용
  CDS-APP-2-iOS/Presentation/HatCategory/Cell/DetailProductCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatCategory/ViewController/HatCategoryViewController.swift
  CDS-APP-2-iOS/Presentation/HatDetail/HatDetailViewController.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/ProductInfo/ProductInfoCollectionViewCell.swift
Labels: Fix, 🐶 가현, Network

#70 [Style] #67 별거 아닌 나의 작고 소중한 수정사항 반영
  CDS-APP-2-iOS.xcodeproj/project.pbxproj
  CDS-APP-2-iOS/Global/Literals/StringLiterals.swift
  CDS-APP-2-iOS/Presentation/HatCategory/Cell/DetailProductCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatCategory/Cell/RealTimeBestCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatCategory/Dummy/MainCategoryDummy.swift
  CDS-APP-2-iOS/Presentation/HatCategory/Enum/HatCategoryLayoutFactory.swift
  CDS-APP-2-iOS/Presentation/HatCategory/ViewController/HatCategoryViewController.swift
  CDS-APP-2-iOS/Presentation/HatDetail/LayoutFactory.swift
Labels: Chore, Style, 😼 서연

#75 HatDetail뷰컨에 커스텀 탭바 구현 완료했습니다.
  CDS-APP-2-iOS.xcodeproj/project.pbxproj
  CDS-APP-2-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CDS-APP-2-iOS/Presentation/HatCategory/ViewController/HatCategoryViewController.swift
  CDS-APP-2-iOS/Presentation/HatDetail/HatDetailViewController.swift
  CDS-APP-2-iOS/Presentation/Tabbar/HatDetailTabbarView.swift
Labels: Feat, 😼 서연
