Repository DO-SOPT-CDS-APP-2/CDS-APP-2-iOS, pull requests merged in 2023-11, with the labels that each got.

#8 Feat [#5] - navigation bar 구현
  CDS-APP-2-iOS.xcodeproj/project.pbxproj
  CDS-APP-2-iOS/Presentation/HatDetail/HatDetailViewController.swift
  CDS-APP-2-iOS/Presentation/HatDetail/LayoutFactory.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/InquireInfoCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/MainInfoCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/ProductInfoCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/RecommendInfoCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/ReviewInfoCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/SizeInfoCollectionViewCell.swift
Labels: Feat, 🐶 가현

#10 Feat [#7] Category TableView 구현
  CDS-APP-2-iOS.xcodeproj/project.pbxproj
  CDS-APP-2-iOS/Application/SceneDelegate.swift
  CDS-APP-2-iOS/Global/Extension/CALayer+.swift
  CDS-APP-2-iOS/Global/Literals/ImageLiterals.swift
  CDS-APP-2-iOS/Global/Literals/StringLiterals.swift
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/imgLoveMeMonster.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/imgLoveMeMonster.imageset/스크린샷 2023-11-10 오후 7.53 2.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/imgLoveMeMonster.imageset/스크린샷 2023-11-10 오후 7.53 2@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/imgLoveMeMonster.imageset/스크린샷 2023-11-10 오후 7.53 2@3x.png
  CDS-APP-2-iOS/Presentation/Category/Cell/CategoryDetailTableViewCell.swift
  CDS-APP-2-iOS/Presentation/Category/Cell/CategoryHorizontalCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/Category/Cell/CategoryTableViewCell.swift
  CDS-APP-2-iOS/Presentation/Category/Dummy/CategoryDetailList.swift
  CDS-APP-2-iOS/Presentation/Category/Dummy/CategoryList.swift
  CDS-APP-2-iOS/Presentation/Category/View/CategoryDetailTableHeaderView.swift
  CDS-APP-2-iOS/Presentation/Category/View/CategoryHeaderView.swift
  CDS-APP-2-iOS/Presentation/Category/View/CategoryTableView.swift
  CDS-APP-2-iOS/Presentation/Category/ViewController/CategoryViewController.swift
Labels: Feat, 🐰 희주

#11 Feat [#4] Custom Tabbar 구현
  CDS-APP-2-iOS.xcodeproj/project.pbxproj
  CDS-APP-2-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CDS-APP-2-iOS/Global/Literals/ImageLiterals.swift
  CDS-APP-2-iOS/Global/Literals/StringLiterals.swift
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/ic_home_off.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/ic_home_off.imageset/ic_home_on.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/ic_home_off.imageset/ic_home_on@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/ic_home_off.imageset/ic_home_on@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/ic_home_on.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/ic_home_on.imageset/ic_home_on-1.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/ic_home_on.imageset/ic_home_on@2x-1.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/ic_home_on.imageset/ic_home_on@3x-1.png
  CDS-APP-2-iOS/Presentation/Tabbar/TabbarController.swift
  CDS-APP-2-iOS/Presentation/Tabbar/TabbarItem.swift
Labels: Feat, 😼 서연

#16 Feat [#15] 이미지 에셋 추가 및 NavigationBar 설정
  CDS-APP-2-iOS.xcodeproj/project.pbxproj
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/imgLoveMe.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/imgLoveMe.imageset/imgLoveMe 2@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/imgLoveMe.imageset/imgLoveMe 2@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/imgLoveMe.imageset/imgLoveMe.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/imgLoveMe.imageset/스크린샷 2023-11-10 오후 7.53 2.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/imgLoveMe.imageset/스크린샷 2023-11-10 오후 7.53 2@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/imgLoveMe.imageset/스크린샷 2023-11-10 오후 7.53 2@3x.png
  CDS-APP-2-iOS/Presentation/Tabbar/TabbarController.swift
Labels: Chore, 🐰 희주

#17 [Feat] #12 HomeTopView 구현 완료
  CDS-APP-2-iOS.xcodeproj/project.pbxproj
  CDS-APP-2-iOS/Global/Extension/UIButton+.swift
  CDS-APP-2-iOS/Global/Extension/UIStackView+.swift
  CDS-APP-2-iOS/Global/Literals/StringLiterals.swift
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_logo.imageset/img_logo.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_logo.imageset/img_logo@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_logo.imageset/img_logo@3x.png
  CDS-APP-2-iOS/Presentation/Category/ViewController/CategoryViewController.swift
  CDS-APP-2-iOS/Presentation/Home/View/ChipView.swift
  CDS-APP-2-iOS/Presentation/Home/View/HomeTopView.swift
  CDS-APP-2-iOS/Presentation/Home/ViewController.swift
  CDS-APP-2-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: Feat, 🐹 윤빈

#18 [Feat] #13 HatCategory 고정 헤더뷰 구현
  CDS-APP-2-iOS.xcodeproj/project.pbxproj
  CDS-APP-2-iOS/Application/SceneDelegate.swift
  CDS-APP-2-iOS/Global/Extension/NavigationController+.swift
  CDS-APP-2-iOS/Global/Literals/ImageLiterals.swift
  CDS-APP-2-iOS/Global/Literals/StringLiterals.swift
  CDS-APP-2-iOS/Presentation/HatCategory/Cell/HeaderCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatCategory/Dummy/HeaderCategoryDummy.swift
  CDS-APP-2-iOS/Presentation/HatCategory/ViewController/HatCategoryViewController.swift
  CDS-APP-2-iOS/Presentation/Tabbar/TabbarController.swift
Labels: Feat, 😼 서연

#19 [Feat] #9 HatDetail 1번째 Cell 구현
  CDS-APP-2-iOS.xcodeproj/project.pbxproj
  CDS-APP-2-iOS/Global/Literals/ImageLiterals.swift
  CDS-APP-2-iOS/Global/Literals/StringLiterals.swift
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hat.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hat.imageset/Rectangle 1.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hat.imageset/Rectangle 2.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hat.imageset/Rectangle.png
  CDS-APP-2-iOS/Presentation/HatDetail/HatDetailViewController.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/InquireInfo/InquireInfoCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/MainInfo/MainInfoCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/MainInfoCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/ProductInfo/ProductInfoCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/ProductInfo/ProductInfoFooterCollectionReusableView.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/ProductInfo/ProductInfoHeaderCollectionReusableView.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/RecommendInfo/RecommendInfoCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/ReviewInfo/ReviewInfoCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/SizeInfo/SizeInfoCollectionViewCell.swift
Labels: Feat, 🐶 가현

#23 [Feat] #20 HatDetail 2번째 Cell, Sticky Header 구현 완료
  CDS-APP-2-iOS/Global/Literals/ImageLiterals.swift
  CDS-APP-2-iOS/Global/Literals/StringLiterals.swift
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hat2.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hat2.imageset/Vector 1.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hat2.imageset/Vector 2.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hat2.imageset/Vector.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatmodel.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatmodel.imageset/Vector 1.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatmodel.imageset/Vector 2.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatmodel.imageset/Vector.png
  CDS-APP-2-iOS/Presentation/HatDetail/HatDetailViewController.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/MainInfo/MainInfoCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/ProductInfo/ProductInfoCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/ProductInfo/ProductInfoHeaderCollectionReusableView.swift
Labels: Feat, 🐶 가현

#24 [Feat] #21 HomeCollectionView 첫번째 섹션 구현 완료
  CDS-APP-2-iOS.xcodeproj/project.pbxproj
  CDS-APP-2-iOS/Application/SceneDelegate.swift
  CDS-APP-2-iOS/Global/Literals/ImageLiterals.swift
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_1.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_1.imageset/img_home_1.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_1.imageset/img_home_1@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_1.imageset/img_home_1@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_65.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_65.imageset/img_home_65.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_65.imageset/img_home_65@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_65.imageset/img_home_65@3x.png
  CDS-APP-2-iOS/Presentation/Home/Enum/HomeLayoutFactory.swift
  CDS-APP-2-iOS/Presentation/Home/Enum/HomeSection.swift
  CDS-APP-2-iOS/Presentation/Home/View/Cell/HomeCardCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/Home/View/HomeView.swift
  CDS-APP-2-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: Feat, 🐹 윤빈

#28 [Add] #26 HatDetail MainInfo detail View 구현 완료
  CDS-APP-2-iOS.xcodeproj/project.pbxproj
  CDS-APP-2-iOS/Global/Literals/ImageLiterals.swift
  CDS-APP-2-iOS/Global/Literals/StringLiterals.swift
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatdetail.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatdetail.imageset/img_hatdetail_2.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatdetail.imageset/img_hatdetail_2@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatdetail.imageset/img_hatdetail_2@3x.png
  CDS-APP-2-iOS/Presentation/HatDetail/HatDetailViewController.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/MainInfo/MainInfoCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/MainInfo/MainInfoDetailView.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/ProductInfo/ProductInfoCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/ProductInfo/ProductInfoFooterCollectionReusableView.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/ProductInfo/ProductInfoHeaderCollectionReusableView.swift
Labels: 🐶 가현, Add

#35 [Feat] #22 HatCategory 스크롤영역의 첫번째 섹션 구현 완료
  CDS-APP-2-iOS.xcodeproj/project.pbxproj
  CDS-APP-2-iOS/Application/SceneDelegate.swift
  CDS-APP-2-iOS/Global/Literals/ImageLiterals.swift
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/realtimeBestImage/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/realtimeBestImage/img_hatcategory_1.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/realtimeBestImage/img_hatcategory_1.imageset/img_hatcategory_1.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/realtimeBestImage/img_hatcategory_1.imageset/img_hatcategory_1@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/realtimeBestImage/img_hatcategory_1.imageset/img_hatcategory_1@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/realtimeBestImage/img_hatcategory_2.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/realtimeBestImage/img_hatcategory_2.imageset/img_hatcategory_2.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/realtimeBestImage/img_hatcategory_2.imageset/img_hatcategory_2@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/realtimeBestImage/img_hatcategory_2.imageset/img_hatcategory_2@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/realtimeBestImage/img_hatcategory_3.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/realtimeBestImage/img_hatcategory_3.imageset/img_hatcategory_3.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/realtimeBestImage/img_hatcategory_3.imageset/img_hatcategory_3@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/realtimeBestImage/img_hatcategory_3.imageset/img_hatcategory_3@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/realtimeBestImage/img_hatcategory_4.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/realtimeBestImage/img_hatcategory_4.imageset/img_hatcategory_4.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/realtimeBestImage/img_hatcategory_4.imageset/img_hatcategory_4@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/realtimeBestImage/img_hatcategory_4.imageset/img_hatcategory_4@3x.png
  CDS-APP-2-iOS/Presentation/HatCategory/Cell/HeaderCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatCategory/Cell/RealTimeBestCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatCategory/Dummy/HeaderCategoryDummy.swift
  CDS-APP-2-iOS/Presentation/HatCategory/Dummy/MainCategoryDummy.swift
  CDS-APP-2-iOS/Presentation/HatCategory/Enum/HatCategoryLayoutFactory.swift
  CDS-APP-2-iOS/Presentation/HatCategory/View/HatCategoryMainView.swift
  CDS-APP-2-iOS/Presentation/HatCategory/ViewController/HatCategoryViewController.swift
  CDS-APP-2-iOS/Presentation/Tabbar/TabbarController.swift
Labels: Feat, 😼 서연

#37 [Feat] #34 HomeCollectionVIew 네번째 Section 구현 완료
  CDS-APP-2-iOS.xcodeproj/project.pbxproj
  CDS-APP-2-iOS/Global/Literals/ImageLiterals.swift
  CDS-APP-2-iOS/Global/Literals/StringLiterals.swift
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_10.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_10.imageset/img_home_10.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_10.imageset/img_home_10@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_10.imageset/img_home_10@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_11.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_11.imageset/img_home_11.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_11.imageset/img_home_11@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_11.imageset/img_home_11@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_12.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_12.imageset/img_home_12.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_12.imageset/img_home_12@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_12.imageset/img_home_12@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_13.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_13.imageset/img_home_11.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_13.imageset/img_home_11@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_13.imageset/img_home_11@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_2.imageset/Contents 2.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_3.imageset/Contents 2.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_8.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_8.imageset/img_home_8.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_8.imageset/img_home_8@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_8.imageset/img_home_8@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_9.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_9.imageset/img_home_9.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_9.imageset/img_home_9@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_home_9.imageset/img_home_9@3x.png
  CDS-APP-2-iOS/Presentation/Home/Enum/HomeLayoutFactory.swift
  CDS-APP-2-iOS/Presentation/Home/Enum/HomeSection.swift
  CDS-APP-2-iOS/Presentation/Home/View/Cell/HomeProductCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/Home/View/Data/ProductCellData.swift
  CDS-APP-2-iOS/Presentation/Home/View/Reusable/HomePromotionReusableView.swift
  CDS-APP-2-iOS/Presentation/Home/View/Reusable/HomeSeeAllReusableView.swift
  CDS-APP-2-iOS/Presentation/Home/View/Reusable/HomeTitleReusableView.swift
  CDS-APP-2-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: Feat, 🐹 윤빈

#39 [Feat] #36 HatCategory 스크롤 영역 두번째 컬렉션뷰 구현 완료
  CDS-APP-2-iOS.xcodeproj/project.pbxproj
  CDS-APP-2-iOS/Global/Literals/StringLiterals.swift
  CDS-APP-2-iOS/Presentation/HatCategory/Cell/FilterCategoryCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatCategory/Dummy/MainCategoryDummy.swift
  CDS-APP-2-iOS/Presentation/HatCategory/View/HatCategoryMainView.swift
  CDS-APP-2-iOS/Presentation/HatCategory/ViewController/HatCategoryViewController.swift
Labels: Feat, 😼 서연

#41 [Feat] #33 - HatDetail RecommendInfoCollectionView 구현 완료
  CDS-APP-2-iOS.xcodeproj/project.pbxproj
  CDS-APP-2-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CDS-APP-2-iOS/Global/Literals/ImageLiterals.swift
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_event1.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_event1.imageset/img_hatdetail_8.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_event1.imageset/img_hatdetail_8@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_event1.imageset/img_hatdetail_8@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_event2.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_event2.imageset/img_hatdetail_9.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_event2.imageset/img_hatdetail_9@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_event2.imageset/img_hatdetail_9@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_event3.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_event3.imageset/img_hatdetail_10.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_event3.imageset/img_hatdetail_10@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_event3.imageset/img_hatdetail_10@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_event4.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_event4.imageset/img_hatdetail_11.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_event4.imageset/img_hatdetail_11@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_event4.imageset/img_hatdetail_11@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatrecommend1.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatrecommend1.imageset/img_hatdetail_4.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatrecommend1.imageset/img_hatdetail_4@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatrecommend1.imageset/img_hatdetail_4@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatrecommend2.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatrecommend2.imageset/img_hatdetail_5.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatrecommend2.imageset/img_hatdetail_5@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatrecommend2.imageset/img_hatdetail_5@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatrecommend3.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatrecommend3.imageset/img_hatdetail_6.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatrecommend3.imageset/img_hatdetail_6@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatrecommend3.imageset/img_hatdetail_6@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatrecommend4.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatrecommend4.imageset/img_hatdetail_7.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatrecommend4.imageset/img_hatdetail_7@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatrecommend4.imageset/img_hatdetail_7@3x.png
  CDS-APP-2-iOS/Presentation/HatDetail/HatDetailViewController.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/RecommendInfo/FirstRecommend/FirstDetailCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/RecommendInfo/FirstRecommend/FirstRecommendCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/RecommendInfo/FirstRecommend/RecommendItem.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/RecommendInfo/RecommendInfoCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/RecommendInfo/RecommendInfoHeaderCollectionReusableView.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/RecommendInfo/SecondRecommend/EventItem.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/RecommendInfo/SecondRecommend/SecondDetailCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/RecommendInfo/SecondRecommend/SecondRecommendCollectionViewCell.swift
Labels: Feat, 🐶 가현

#44 [Feat] #42 - HatDetail ReviewInfoCollectionView Cell 구현
  CDS-APP-2-iOS.xcodeproj/project.pbxproj
  CDS-APP-2-iOS/Application/SceneDelegate.swift
  CDS-APP-2-iOS/Global/Literals/ImageLiterals.swift
  CDS-APP-2-iOS/Global/Literals/StringLiterals.swift
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview1.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview1.imageset/img_hatdetail_12.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview1.imageset/img_hatdetail_12@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview1.imageset/img_hatdetail_12@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview2.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview2.imageset/img_hatdetail_13.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview2.imageset/img_hatdetail_13@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview2.imageset/img_hatdetail_13@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview3.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview3.imageset/img_hatdetail_14.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview3.imageset/img_hatdetail_14@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview3.imageset/img_hatdetail_14@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview4.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview4.imageset/img_hatdetail_15.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview4.imageset/img_hatdetail_15@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview4.imageset/img_hatdetail_15@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview5.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview5.imageset/img_hatdetail_16.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview5.imageset/img_hatdetail_16@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview5.imageset/img_hatdetail_16@3x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview6.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview6.imageset/img_hatdetail_17.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview6.imageset/img_hatdetail_17@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_hatreview6.imageset/img_hatdetail_17@3x.png
  CDS-APP-2-iOS/Presentation/HatDetail/HatDetailViewController.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/ReviewInfo/ReviewInfoCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/ReviewInfo/ReviewInfoHeaderCollectionReusableView.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/ReviewInfo/ReviewPhotoCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/ReviewInfo/ReviewPhotoItem.swift
Labels: Feat, 🐶 가현

#47 [Feat] #43 - HatDetail InquireInfoCollectionView 마지막 Cell 구현
  CDS-APP-2-iOS.xcodeproj/project.pbxproj
  CDS-APP-2-iOS/Global/Literals/ImageLiterals.swift
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_inquire.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_inquire.imageset/img_hatdetail_4.svg
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_inquire.imageset/img_hatdetail_4@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_inquire.imageset/img_hatdetail_4@3x.png
  CDS-APP-2-iOS/Presentation/HatDetail/HatDetailViewController.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/InquireInfo/InquireInfoCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/InquireInfo/InquireInfoHeaderCollectionReusableView.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/InquireInfo/InquireList.swift
  CDS-APP-2-iOS/Presentation/HatDetail/cell/InquireInfo/ListCollectionViewCell.swift
Labels: Feat, 🐶 가현

#52 [Feat] #48 - Button 클릭 시 최상단으로 뷰 이동 구현
  CDS-APP-2-iOS/Global/Literals/ImageLiterals.swift
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_btnUP.imageset/Contents.json
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_btnUP.imageset/btn_up.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_btnUP.imageset/btn_up@2x.png
  CDS-APP-2-iOS/Global/Resources/Assets.xcassets/img_btnUP.imageset/btn_up@3x.png
  CDS-APP-2-iOS/Presentation/HatDetail/HatDetailViewController.swift
Labels: Feat, 🐶 가현

#58 [ Network] #57 HomeCollectionView 세번째 Section API 통신 완료
  CDS-APP-2-iOS.xcodeproj/project.pbxproj
  CDS-APP-2-iOS/Global/Extension/UIImageView+.swift
  CDS-APP-2-iOS/Global/Literals/StringLiterals.swift
  CDS-APP-2-iOS/Network/Home/DTO/PromotionDataModel.swift
  CDS-APP-2-iOS/Network/Home/DTO/a.swift
  CDS-APP-2-iOS/Network/Home/Sevice/HomePromotionService.swift
  CDS-APP-2-iOS/Network/Home/Sevice/x.swift
  CDS-APP-2-iOS/Presentation/Home/Data/PopularCellData.swift
  CDS-APP-2-iOS/Presentation/Home/Data/ProductCellData.swift
  CDS-APP-2-iOS/Presentation/Home/Data/PromotionCellData.swift
  CDS-APP-2-iOS/Presentation/Home/Data/PromotionHeaderData.swift
  CDS-APP-2-iOS/Presentation/Home/Data/RecommendSmallCellData.swift
  CDS-APP-2-iOS/Presentation/Home/View/Cell/HomePromotionCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: 🐹 윤빈, Network

#63 [Network] #61 KingFisher 적용, 탭바 연결
  CDS-APP-2-iOS.xcodeproj/project.pbxproj
  CDS-APP-2-iOS/Global/Extension/NavigationController+.swift
  CDS-APP-2-iOS/Global/Literals/StringLiterals.swift
  CDS-APP-2-iOS/Network/Home/Sevice/HomePromotionService.swift
  CDS-APP-2-iOS/Presentation/Category/ViewController/CategoryViewController.swift
  CDS-APP-2-iOS/Presentation/HatCategory/Cell/DetailProductCollectionViewCell.swift
  CDS-APP-2-iOS/Presentation/HatCategory/ViewController/HatCategoryViewController.swift
  CDS-APP-2-iOS/Presentation/HatDetail/HatDetailViewController.swift
  CDS-APP-2-iOS/Presentation/Tabbar/TabbarController.swift
  CDS-APP-2-iOS/Presentation/Tabbar/TabbarItem.swift
Labels: Feat, 😼 서연, Network
